### ISSUE TITLE
Number of typed reads exceeding number of mapped reads 

### ISSUE THREAD

**Issue by agshumate** [bioforensics/MicroHapulator#171]
Reads are being double (or triple, or quadruple etc.) counted if they are successfully typed for different marker versions at the same locus. This leads to the number of typed reads exceeding the number of mapped reads. See picture below. We should instead report the number of _unique_ mapped reads. 

<img width="1089" alt="image" src="https://github.com/bioforensics/MicroHapulator/assets/29218752/f64388d4-6b19-45ae-b21e-71040c9a011d">

**Comment by standage** [comment]
Good catch!
